# Generated by Django 3.2.9 on 2022-01-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='messageModel',
        ),
        migrations.RenameModel(
            old_name='Room',
            new_name='roomModel',
        ),
    ]
