# Generated by Django 3.2.9 on 2022-01-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclass',
            name='video',
            field=models.FileField(upload_to='video/%y/'),
        ),
    ]
