# Generated by Django 3.2.9 on 2022-01-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('topicName', models.CharField(max_length=200)),
                ('submissionDate', models.DateField()),
                ('submissionTime', models.TimeField()),
                ('files', models.FileField(upload_to='files/%y')),
            ],
        ),
    ]
