# Generated by Django 3.2.9 on 2022-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionroom',
            name='roomPrivacy',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=200, null=True),
        ),
    ]
