# Generated by Django 3.2.9 on 2022-01-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_discussionroom_roomprivacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionroom',
            old_name='hostName',
            new_name='userName',
        ),
    ]
