# Generated by Django 3.2.9 on 2022-01-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_hostname_discussionroom_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionroom',
            old_name='userName',
            new_name='host',
        ),
    ]
