# Generated by Django 3.2.9 on 2022-01-07 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_alter_discussionroom_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionroom',
            name='roomParticipants',
            field=models.ManyToManyField(blank=True, related_name='roomParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
