# Generated by Django 3.2.9 on 2022-01-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questionAndAnsweer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('answerSheet', models.FileField(upload_to='questionAndAnsweer/answerSheet/')),
            ],
        ),
    ]
