# Generated by Django 3.2.9 on 2022-01-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionAndSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('solution', models.FileField(upload_to='questionAndSolution/solution/')),
            ],
        ),
        migrations.DeleteModel(
            name='questionAndAnsweer',
        ),
    ]
