# Generated by Django 3.2.9 on 2022-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20220105_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandsolution',
            name='question',
            field=models.FileField(blank=True, null=True, upload_to='questionAndSolution/question/'),
        ),
    ]
