# Generated by Django 4.0 on 2022-01-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutioncode',
            name='codeFile',
            field=models.FileField(null=True, upload_to='codeFile/'),
        ),
        migrations.AlterField(
            model_name='solutioncode',
            name='codeName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solutioncode',
            name='codeUploadedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
