# Generated by Django 4.0 on 2022-01-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
