# Generated by Django 4.0 on 2022-01-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0005_customer_delete_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='userEmail',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='userPhone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='fullName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='userName',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
