# Generated by Django 4.0 on 2022-01-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0007_remove_customer_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='userAccount',
        ),
    ]
