# Generated by Django 3.2.9 on 2022-01-11 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='questionModel',
        ),
        migrations.RenameModel(
            old_name='Response',
            new_name='responseOnQuestion',
        ),
    ]
