# Generated by Django 3.2.9 on 2022-01-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220111_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='created_at',
            new_name='questionCreatedAt',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='updated_at',
            new_name='questionUpdatedAt',
        ),
        migrations.RenameField(
            model_name='responseonquestion',
            old_name='created_at',
            new_name='responseCreatedAt',
        ),
        migrations.RenameField(
            model_name='responseonquestion',
            old_name='updated_at',
            new_name='responseUpdatedAt',
        ),
    ]
